--liquibase formatted sql

--changeset renanpelicari:5
CREATE TABLE T_MONEY_TRANSFER_HISTORY (
    ID SERIAL PRIMARY KEY,
    TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    SOURCE_ACCOUNT_ID INTEGER REFERENCES T_ACCOUNT(id),
    TARGET_ACCOUNT_ID INTEGER REFERENCES T_ACCOUNT(id),
    AMOUNT NUMERIC NOT NULL,
    OPERATION_PRICE NUMERIC,
    DESCRIPTION VARCHAR(150),
    ZONE_DATETIME TIMESTAMP NOT NULL
);
--rollback drop table T_MONEY_TRANSFER_HISTORY;
