CREATE TABLE T_ACCOUNT_TRANSFER_HIST (
    ID SERIAL PRIMARY KEY,
    TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    SOURCE_ACCOUNT_ID INTEGER REFERENCES T_ACCOUNT(id),
    TARGET_ACCOUNT_ID INTEGER REFERENCES T_ACCOUNT(id),
    AMOUNT NUMERIC NOT NULL,
    OPERATION_PRICE NUMERIC,
    DESCRIPTION VARCHAR(150),
    ZONE_DATETIME TIMESTAMPTZ NOT NULL
)
